### ISSUE TITLE
Vulkan Resizing

### ISSUE THREAD

**Issue by Behemyth** [Synodic-Software/Soul-Engine#216]
When you try resizing the window Soul Engine crashes. This is because resizing is not yet supported. When a resize occurs, a resizing event occurs in the GLFW window and is passed along to the VulkanSwapchain object in `Soul Engine\Source\Rasterer\Graphics API\Vulkan\VulkanSwapChain`. 

Helpful links:
https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation (but use the C++ bindings)

**Comment by benjaminrsherman** [comment]
The window can now be resized.  On Linux, the image is redrawn smoothly as the image is resized.  On Windows, the image remains static until the window resize is complete.

Extremely rapid resizing of the window _may_ cause Vulkan to crash due to one of several errors, however rectifying this issue would require retooling the entire Vulkan system to support faster swapchain recreation.
